baseURL = 'http://Rwatana.github.io/Hugo-repo'
languageCode = 'ja'
title = 'Self Introduction'
theme = "ananke"
hasCJKLanguage = true
[params]
  text_color = 'dark-gray'
  background_color_class = 'bg-navy'
  author = 'Rwatana'
  favicon = '/static/images/screenshot.png'
  site_logo = '/static/images/icon.png'

[[params.ananke_socials]]
  name = 'github'
  url  = 'https://github.com/Rwatana'