baseURL = 'http://Rwatana.github.io/Hugo-repo'
languageCode = 'ja'
title = 'Self Introduction'
theme = "ananke"
hasCJKLanguage = true
[params]
  text_color = 'dark-gray'
  background_color_class = 'bg-navy'
  author = 'Rwatana'
  favicon = '/images/screenshot.png'
  site_logo = '/images/icon.png'